#!/bin/bash

echo "🚀 ACCEPTING SLACK INVITATIONS"
echo "==============================="
echo ""
echo "Agents invited to Slack:"
echo "1. Ruth (clawdianinan+ruth@gmail.com)"
echo "2. Ngozi (clawdianinan+ngozi@gmail.com)"
echo "3. Cypher (clawdianinan+cypher@gmail.com)"
echo "4. Morpheus (clawdianinan+morpheus@gmail.com)"
echo ""
echo "These are Gmail aliases that forward to: clawdianinan@gmail.com"
echo ""
echo "STEP 1: Open Gmail"
open "https://mail.google.com"
echo ""
echo "STEP 2: Search for Slack invitations"
echo "   Search query: 'from:slack invitation to join'"
echo ""
echo "STEP 3: For each invitation email:"
echo "   1. Open the email"
echo "   2. Click 'Join Clawdia'\''s Agents'"
echo "   3. If prompted to sign in, use:"
echo "      - Email: clawdianinan@gmail.com"
echo "      - Password: [Gmail password]"
echo "   4. Accept the invitation"
echo ""
echo "STEP 4: Verify all 4 agents are in Slack"
echo "   After accepting, check: https://clawdiasagents.slack.com"
echo ""
echo "Estimated time: 5-10 minutes"
echo ""
echo "Once complete, all 10 agents will be active in Slack!"
echo ""
echo "Note: If Gmail shows separate emails for each alias,"
echo "      you may need to accept each one separately."
echo ""
echo "Ready to proceed? The invitations should be in your inbox now."