#!/bin/bash
# Complete Slack Invitations - Manual Process Guide
# This script provides step-by-step instructions for completing Slack invitations

echo "🚀 COMPLETE SLACK INVITATIONS - MANUAL PROCESS"
echo "=============================================="
echo ""
echo "📋 **Current Status:**"
echo "• Workspace: clawdiasagents.slack.com"
echo "• Existing agents: 6 (Trinity, Fela, Shuri, Ebun, Nova, Sheba)"
echo "• Missing agents: 4 (Ruth, Ngozi, Cypher, Morpheus)"
echo "• Admin account: clawdianinan@gmail.com"
echo ""
echo "🎯 **Task:** Invite remaining 4 agents and create project channels"
echo "⏱️  **Estimated time:** 10-15 minutes"
echo ""

echo "📝 **STEP 1: LOG IN TO SLACK**"
echo "-----------------------------"
echo "1. Open https://clawdiasagents.slack.com"
echo "2. Log in as: clawdianinan@gmail.com"
echo "3. Verify you're in the correct workspace"
echo ""

echo "📧 **STEP 2: INVITE MISSING AGENTS**"
echo "-----------------------------------"
echo "1. Click 'Invite people to Clawdia'\'s Agents' in sidebar"
echo "2. Enter these 4 emails:"
echo "   • clawdianinan+ruth@gmail.com"
echo "   • clawdianinan+ngozi@gmail.com"
echo "   • clawdianinan+cypher@gmail.com"
echo "   • clawdianinan+morpheus@gmail.com"
echo "3. Click 'Send Invitations'"
echo "4. Note: Invitations will be sent to clawdianinan@gmail.com"
echo ""

echo "📁 **STEP 3: CREATE PROJECT CHANNELS**"
echo "-------------------------------------"
echo "1. Click '+' next to 'Channels' in sidebar"
echo "2. Create these channels (make private for project work):"
echo ""
echo "   Channel Name    | Purpose"
echo "   ----------------|----------------------------------------"
echo "   #development    | Development work (Trinity, Morpheus, Cypher)"
echo "   #design         | Design work (Fela)"
echo "   #documentation  | Documentation (Ebun)"
echo "   #compliance     | Compliance work (Ruth, Ngozi)"
echo "   #operations     | Operations (Shuri, Nova)"
echo "   #testing        | Testing/QA (Morpheus)"
echo "   #security       | Security (Cypher)"
echo ""
echo "3. Add appropriate descriptions for each channel"
echo ""

echo "📨 **STEP 4: ACCEPT INVITATIONS**"
echo "--------------------------------"
echo "1. Check clawdianinan@gmail.com inbox"
echo "2. Look for emails from 'slack.com' or 'clawdiasagents.slack.com'"
echo "3. Open each invitation email (4 total)"
echo "4. Click 'Join Now' in each email"
echo "5. Complete Slack signup for each agent"
echo ""

echo "👥 **STEP 5: ADD AGENTS TO CHANNELS**"
echo "------------------------------------"
echo "1. For each channel created in Step 3:"
echo "   a. Open the channel"
echo "   b. Click 'Add people'"
echo "   c. Add the appropriate agents:"
echo ""
echo "   Channel       | Add These Agents"
echo "   --------------|--------------------------------"
echo "   #development  | Trinity, Morpheus, Cypher"
echo "   #design       | Fela"
echo "   #documentation| Ebun"
echo "   #compliance   | Ruth, Ngozi"
echo "   #operations   | Shuri, Nova"
echo "   #testing      | Morpheus"
echo "   #security     | Cypher"
echo ""
echo "2. Also ensure all agents are in:"
echo "   • #prdforge-launch (main project channel)"
echo "   • #agent-coordination (daily standups)"
echo "   • #decisions (key decisions)"
echo "   • #blockers (issues/blockers)"
echo ""

echo "✅ **STEP 6: VERIFY COMPLETION**"
echo "-------------------------------"
echo "1. Go to 'Members' in workspace settings"
echo "2. Verify 10 agents total (6 existing + 4 new)"
echo "3. Check each channel has correct members"
echo "4. Post test message in #prdforge-launch"
echo ""

echo "📊 **STEP 7: DOCUMENT COMPLETION**"
echo "---------------------------------"
echo "1. Update slack-invitation-completion-report.md"
echo "2. Mark tasks as complete in Jira (DEV-26)"
echo "3. Notify team that Slack setup is complete"
echo ""

echo "🆘 **TROUBLESHOOTING**"
echo "---------------------"
echo "• Invitation not received? Check spam folder, resend invitation"
echo "• Can't create channel? Ensure you're workspace admin"
echo "• Agent not showing? Wait 5-10 minutes, refresh page"
echo "• Need help? Refer to docs/slack/agent-invitation-process.md"
echo ""

echo "🎉 **COMPLETION CHECKLIST**"
echo "--------------------------"
echo "[ ] All 4 agents invited"
echo "[ ] All invitations accepted"
echo "[ ] All 7 project channels created"
echo "[ ] Agents added to correct channels"
echo "[ ] Verification complete"
echo "[ ] Documentation updated"
echo ""

echo "📚 **REFERENCE DOCUMENTS**"
echo "-------------------------"
echo "• docs/slack/agent-invitation-process.md"
echo "• docs/slack/agent-channel-assignments.md"
echo "• slack-invitation-completion-report.md"
echo ""

echo "⏰ **TIME TRACKING**"
echo "------------------"
echo "Start time: $(date)"
echo "Expected completion: 10-15 minutes from start"
echo ""

echo "🚀 **READY TO BEGIN?**"
echo "--------------------"
read -p "Press Enter to start the process or Ctrl+C to cancel..."