const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');

// Create a secure directory for wallet storage
const WALLET_DIR = path.join(__dirname, 'wallets');
if (!fs.existsSync(WALLET_DIR)) {
  fs.mkdirSync(WALLET_DIR, { recursive: true });
}

// Generate a new Ethereum wallet
function createEthereumWallet() {
  console.log('🔐 Creating a new Ethereum wallet...\n');
  
  // Create random wallet
  const wallet = ethers.Wallet.createRandom();
  
  // Get wallet details
  const address = wallet.address;
  const privateKey = wallet.privateKey;
  const mnemonic = wallet.mnemonic.phrase;
  
  console.log('✅ Wallet created successfully!\n');
  console.log('📋 Wallet Details:');
  console.log('─────────────────────────────────────────────');
  console.log(`🏷️  Address: ${address}`);
  console.log(`🔑 Private Key: ${privateKey}`);
  console.log(`📝 Mnemonic (12 words): ${mnemonic}`);
  console.log('─────────────────────────────────────────────\n');
  
  // Create wallet info object
  const walletInfo = {
    network: 'Ethereum Mainnet',
    address: address,
    privateKey: privateKey,
    mnemonic: mnemonic,
    createdAt: new Date().toISOString(),
    derivationPath: "m/44'/60'/0'/0/0",
    note: 'Generated by Clawdia AI Wallet Creator'
  };
  
  // Save wallet to file (encrypted in real production)
  const filename = `wallet_${address.substring(0, 10)}_${Date.now()}.json`;
  const filepath = path.join(WALLET_DIR, filename);
  
  fs.writeFileSync(filepath, JSON.stringify(walletInfo, null, 2));
  console.log(`💾 Wallet saved to: ${filepath}`);
  
  // Create a secure backup file (mnemonic only)
  const backupFile = path.join(WALLET_DIR, `backup_${address.substring(0, 10)}.txt`);
  const backupContent = `=== CRYPTO WALLET BACKUP ===
  
IMPORTANT: Keep this information SECRET and SAFE!
Anyone with this information can access your funds.

Wallet Address: ${address}
Mnemonic Phrase: ${mnemonic}

Backup created: ${new Date().toISOString()}
Generated by: Clawdia AI Wallet Creator

=== SECURITY INSTRUCTIONS ===
1. Write down the mnemonic phrase on paper
2. Store in multiple secure locations
3. Never share with anyone
4. Never store digitally (no photos, screenshots, cloud)
5. Consider using a hardware wallet for large amounts
`;
  
  fs.writeFileSync(backupFile, backupContent);
  console.log(`📄 Backup file created: ${backupFile}`);
  
  return walletInfo;
}

// Create a Bitcoin-style wallet (using same mnemonic for demonstration)
function createBitcoinWalletFromMnemonic(mnemonic) {
  console.log('\n💰 Creating Bitcoin wallet from same mnemonic...\n');
  
  // In a real implementation, we would use bitcoinjs-lib
  // For now, we'll show how it would work
  console.log('Note: Bitcoin wallet creation requires bitcoinjs-lib');
  console.log('The same mnemonic can generate Bitcoin addresses using BIP44 path:');
  console.log("Derivation path: m/44'/0'/0'/0/0");
  console.log(`Mnemonic: ${mnemonic}`);
  
  return {
    network: 'Bitcoin Mainnet',
    mnemonic: mnemonic,
    derivationPath: "m/44'/0'/0'/0/0",
    note: 'Use bitcoinjs-lib to generate actual addresses'
  };
}

// Generate wallet recovery phrase
function generateRecoveryPhrase() {
  console.log('\n🔄 Generating standalone recovery phrase...\n');
  
  // Create a wallet just to get a mnemonic
  const wallet = ethers.Wallet.createRandom();
  const mnemonic = wallet.mnemonic.phrase;
  
  console.log('📝 Your 12-word recovery phrase:');
  console.log('─────────────────────────────────────────────');
  const words = mnemonic.split(' ');
  words.forEach((word, index) => {
    console.log(`${index + 1}. ${word}`);
  });
  console.log('─────────────────────────────────────────────\n');
  
  console.log('💡 This phrase can restore wallets on multiple chains:');
  console.log('- Ethereum: m/44\'/60\'/0\'/0/0');
  console.log('- Bitcoin: m/44\'/0\'/0\'/0/0');
  console.log('- BSC: m/44\'/60\'/0\'/0/0');
  console.log('- Polygon: m/44\'/60\'/0\'/0/0');
  
  return mnemonic;
}

// Main function
async function main() {
  console.log('🚀 Clawdia AI Wallet Creator');
  console.log('=============================\n');
  
  // Create Ethereum wallet
  const ethWallet = createEthereumWallet();
  
  // Show Bitcoin wallet info
  createBitcoinWalletFromMnemonic(ethWallet.mnemonic);
  
  // Security warnings
  console.log('\n⚠️  SECURITY WARNINGS:');
  console.log('─────────────────────────────────────────────');
  console.log('1. NEVER share your private key or mnemonic');
  console.log('2. Store mnemonic offline (paper/metal)');
  console.log('3. Test with small amounts first');
  console.log('4. Consider hardware wallet for large amounts');
  console.log('5. This is for educational/demo purposes');
  console.log('─────────────────────────────────────────────\n');
  
  // Show how to use the wallet
  console.log('🔧 How to use this wallet:');
  console.log('1. Import to MetaMask using private key');
  console.log('2. Or restore using the 12-word phrase');
  console.log('3. Send test ETH from a faucet first');
  console.log('4. Check balance on etherscan.io');
  
  // Create a simple HTML page for the wallet
  createWalletHTML(ethWallet);
}

// Create an HTML page to display wallet info (without sensitive data)
function createWalletHTML(walletInfo) {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Clawdia AI Wallet - ${walletInfo.address.substring(0, 10)}...</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f7;
            color: #333;
        }
        .container {
            background: white;
            border-radius: 12px;
            padding: 30px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2d3748;
            border-bottom: 3px solid #4299e1;
            padding-bottom: 10px;
        }
        .wallet-info {
            background: #f7fafc;
            border: 2px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
        }
        .address {
            font-family: monospace;
            font-size: 18px;
            color: #2d3748;
            background: #edf2f7;
            padding: 10px;
            border-radius: 6px;
            word-break: break-all;
        }
        .warning {
            background: #fff5f5;
            border: 2px solid #fc8181;
            color: #c53030;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .success {
            background: #f0fff4;
            border: 2px solid #9ae6b4;
            color: #276749;
            padding: 15px;
            border-radius: 8px;
            margin: 20px 0;
        }
        .qr-placeholder {
            width: 200px;
            height: 200px;
            background: linear-gradient(45deg, #4299e1, #667eea);
            border-radius: 8px;
            margin: 20px auto;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
            font-weight: bold;
        }
        .button {
            background: #4299e1;
            color: white;
            border: none;
            padding: 12px 24px;
            border-radius: 6px;
            font-size: 16px;
            cursor: pointer;
            text-decoration: none;
            display: inline-block;
            margin: 10px 5px;
        }
        .button:hover {
            background: #3182ce;
        }
        .button.secondary {
            background: #718096;
        }
        .button.secondary:hover {
            background: #4a5568;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔐 Clawdia AI Wallet</h1>
        
        <div class="success">
            <strong>✅ Wallet Created Successfully!</strong>
            <p>Your decentralized Ethereum wallet has been generated.</p>
        </div>
        
        <div class="wallet-info">
            <h3>Wallet Address</h3>
            <div class="address">${walletInfo.address}</div>
            
            <h3>Network</h3>
            <p>${walletInfo.network}</p>
            
            <h3>Created</h3>
            <p>${new Date(walletInfo.createdAt).toLocaleString()}</p>
            
            <div class="qr-placeholder">
                QR Code<br>(Would show address QR)
            </div>
        </div>
        
        <div class="warning">
            <strong>⚠️ SECURITY WARNING</strong>
            <p>Your private key and mnemonic phrase have been saved to secure files.</p>
            <p><strong>Never share these with anyone!</strong> They provide full access to your funds.</p>
            <p>Store your mnemonic phrase offline on paper or metal backup.</p>
        </div>
        
        <h3>Next Steps</h3>
        <p>1. Fund your wallet with test ETH from a faucet</p>
        <p>2. Import to MetaMask using private key</p>
        <p>3. Check balance on <a href="https://etherscan.io/address/${walletInfo.address}" target="_blank">Etherscan</a></p>
        
        <div style="margin-top: 30px;">
            <a href="https://etherscan.io/address/${walletInfo.address}" target="_blank" class="button">View on Etherscan</a>
            <a href="https://metamask.io" target="_blank" class="button secondary">Get MetaMask</a>
        </div>
        
        <p style="margin-top: 30px; color: #718096; font-size: 14px;">
            Generated by Clawdia AI on ${new Date().toLocaleString()}<br>
            For educational/demonstration purposes only
        </p>
    </div>
</body>
</html>`;
  
  const htmlFile = path.join(WALLET_DIR, `wallet_${walletInfo.address.substring(0, 10)}.html`);
  fs.writeFileSync(htmlFile, html);
  console.log(`\n🌐 Wallet HTML page created: ${htmlFile}`);
}

// Run the main function
main().catch(console.error);