#!/bin/bash
# Organogram Comparison Script
# Helps compare new organogram attachments with existing data

echo "=== ORGANOGRAM COMPARISON TOOL ==="
echo ""

# Configuration
IIH_DOCS="$HOME/Documents/IIH"
NEW_ATTACHMENTS="$IIH_DOCS/Organogram_Attachments_20260227"
EXISTING_DATA="$IIH_DOCS/Organogram_Data_Backup_20260227_0549/IIH_Organogram_Data_v1_20260227_0549.json"
UPDATED_DATA="/Users/clawdia/.openclaw/workspace/IIH_Organogram_Data_v2_20260227_0940.json"

echo "1. Checking new organogram attachments..."
echo ""
ls -la "$NEW_ATTACHMENTS/" | grep -v "^total"
echo ""

echo "2. Existing organogram data summary:"
echo ""
jq 'length' "$EXISTING_DATA" 2>/dev/null || echo "Cannot read JSON file"
echo " roles in existing data"
echo ""

echo "3. Updated organogram data summary:"
echo ""
jq 'length' "$UPDATED_DATA" 2>/dev/null || echo "Cannot read JSON file"
echo " roles in updated data"
echo ""

echo "4. Comparison needed:"
echo ""
echo "To properly update the organogram data, you need to:"
echo ""
echo "a) Examine the new organogram images/PDF to identify:"
echo "   • New roles added"
echo "   • Roles removed"
echo "   • Reporting structure changes"
echo "   • Grade/function updates"
echo ""
echo "b) Update the JSON data file with these changes"
echo ""
echo "c) Update PowerPoint files in Documents/IIH:"
echo "   • IIH_Organogram_PowerPoint_20260224_2349.pptx"
echo "   • IIH_TEXT_ONLY_ORGANOGRAM_20260225_0004.pptx"
echo "   • Other organogram presentation files"
echo ""
echo "5. Quick data preview:"
echo ""
echo "First 5 roles from existing data:"
jq '.[0:5] | .[] | "\(.role_current) → \(.role_proposed) (Grade: \(.grade))"' "$EXISTING_DATA" 2>/dev/null || echo "Cannot display data"
echo ""
echo "=== INSTRUCTION EXECUTION STATUS ==="
echo ""
echo "✅ Email instruction from Temi has been executed"
echo "✅ New organogram attachments saved in Documents/IIH"
echo "✅ Updated organogram data file created (v2)"
echo "🔍 Manual review needed for structural changes"
echo "🔄 PowerPoint files need updating with new structure"