#!/bin/bash

echo "🔄 Jira API Token Regeneration Helper"
echo "===================================="
echo ""
echo "Current token seems invalid. Let's regenerate it."
echo ""
echo "STEP 1: Generate new API token"
echo "------------------------------"
echo "1. Visit: https://id.atlassian.com/manage-profile/security/api-tokens"
echo "2. Click 'Create API token'"
echo "3. Name: 'PRDForge-Automation'"
echo "4. COPY THE TOKEN (only shown once!)"
echo ""
echo "STEP 2: Update configuration"
echo "---------------------------"
echo "Once you have the new token:"
echo ""
echo "Option A: Update .zshrc"
echo "  nano ~/.zshrc"
echo "  # Find ATLASSIAN_API_TOKEN line"
echo "  # Replace with: export ATLASSIAN_API_TOKEN='NEW_TOKEN_HERE'"
echo "  source ~/.zshrc"
echo ""
echo "Option B: Update .jira.env"
echo "  nano /Users/clawdia/.openclaw/workspace/.jira.env"
echo "  # Replace JIRA_API_TOKEN value"
echo ""
echo "STEP 3: Test new token"
echo "---------------------"
echo "Run: ./test-jira-with-token.sh"
echo ""
echo "STEP 4: Update tickets"
echo "---------------------"
echo "Once token works:"
echo "Run: ./update-jira-tickets-complete.sh"
echo ""
echo "Common issues:"
echo "1. Token must be copied exactly (no spaces)"
echo "2. Token expires if not used for long periods"
echo "3. Account must be active and verified"
echo "4. Token needs 'read' and 'write' permissions"